"""
dict_ingredient.py

Seeds product_catalog.ingredient from OpenFoodFacts taxonomy files
(ingredients.txt, additives.txt) and structured metadata (ingredients.json).

Populates: name, name_ru, description, e_number, category, is_allergen,
           is_additive, risk_level.

is_additive = True  for entries that appear in additives.txt taxonomy.
risk_level  = 0..3  generated by LLM for additives; 0 for non-additives.
              0=safe, 1=caution, 2=moderate risk, 3=danger/banned.
              LLM results cached in .risk_level_cache.json — safe to re-run.

Idempotent via ON CONFLICT (name) DO UPDATE.

Usage:
    python dds/dict_ingredient.py
"""

import json
import logging
import os
import re

import psycopg2
from psycopg2.extras import execute_values
from openai import OpenAI
from pydantic import BaseModel
from tqdm import tqdm

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import DB_CONFIG, OPENAI_API_KEY

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
INGREDIENTS_JSON = os.path.join(PROJECT_DIR, "ingredients.json")
INGREDIENTS_TXT = os.path.join(PROJECT_DIR, "ingredients.txt")
ADDITIVES_TXT = os.path.join(PROJECT_DIR, "additives.txt")
RISK_CACHE_FILE = os.path.join(SCRIPT_DIR, ".risk_level_cache.json")

E_CODE_RE = re.compile(r"^e\d", re.IGNORECASE)

BATCH_SIZE = 80  # additives per LLM call


# ---------------------------------------------------------------------------
# Taxonomy parsing
# ---------------------------------------------------------------------------

def parse_taxonomy_txt(filepath: str) -> dict[str, dict]:
    """
    Parse OpenFoodFacts taxonomy .txt file.
    Returns: {canonical_id: {en: [...], ru: [...]}}
    """
    entries: dict[str, dict] = {}

    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    block_lines: list[str] = []

    def process_block(block: list[str]):
        en_names: list[str] = []
        ru_names: list[str] = []

        for bline in block:
            bline = bline.rstrip("\n")
            if bline.startswith("#") or bline.startswith("< "):
                continue
            if re.match(r"^[a-z][a-z0-9_]*:", bline) and not re.match(
                r"^[a-z]{2}(_[a-z]{2})?: ", bline
            ):
                continue
            m = re.match(r"^([a-z]{2}(?:_[a-z]{2})?): (.+)$", bline)
            if m:
                lang = m.group(1)
                values = [v.strip() for v in m.group(2).split(",") if v.strip()]
                if lang == "en":
                    en_names.extend(values)
                elif lang == "ru":
                    ru_names.extend(values)

        if en_names:
            canonical = "en:" + en_names[0].lower().replace(" ", "-")
            if canonical in entries:
                entries[canonical]["en"] = list(
                    set(entries[canonical]["en"]) | set(en_names)
                )
                entries[canonical]["ru"] = list(
                    set(entries[canonical]["ru"]) | set(ru_names)
                )
            else:
                entries[canonical] = {"en": en_names, "ru": ru_names}

    for line in lines:
        stripped = line.strip()
        if not stripped:
            if block_lines:
                process_block(block_lines)
                block_lines = []
        else:
            block_lines.append(line)

    if block_lines:
        process_block(block_lines)

    return entries


def pick_best_ru(txt_ru: list[str], json_name_ru: str | None) -> str | None:
    for syn in txt_ru:
        if not E_CODE_RE.match(syn.strip()):
            return syn.strip()
    if json_name_ru and not E_CODE_RE.match(json_name_ru.strip()):
        return json_name_ru.strip()
    return None


# ---------------------------------------------------------------------------
# LLM risk scoring
# ---------------------------------------------------------------------------

class AdditiveRisk(BaseModel):
    canonical_id: str
    risk_level: int  # 0–3


class AdditiveRiskBatch(BaseModel):
    additives: list[AdditiveRisk]


SYSTEM_PROMPT = """\
You are a food safety expert. For each food additive, assign risk_level:
  0 = safe            — approved, well-studied, no known health concerns
  1 = caution         — permitted but some population groups should limit intake
  2 = moderate risk   — controversial, potential harmful effects at typical doses, or banned in some countries
  3 = danger/banned   — known harmful effects, banned by major food safety authorities (EU/FDA/WHO)

Return EVERY additive from the input with its canonical_id and risk_level.
Do not skip any. Be consistent with established food safety science.\
"""


def score_additives_llm(
    client: OpenAI,
    additives: list[tuple[str, str, str | None]],  # (canonical_id, name, e_number)
) -> dict[str, int]:
    """Call LLM to score a batch of additives. Returns {canonical_id: risk_level}."""
    lines = []
    for cid, name, e_num in additives:
        e_str = f", e_number: {e_num}" if e_num else ""
        lines.append(f"canonical_id: {cid}, name: {name}{e_str}")
    user_content = "\n".join(lines)

    try:
        completion = client.beta.chat.completions.parse(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ],
            response_format=AdditiveRiskBatch,
            temperature=0.0,
        )
        parsed = completion.choices[0].message.parsed
        return {item.canonical_id: max(0, min(3, item.risk_level)) for item in parsed.additives}
    except Exception as e:
        log.error("LLM batch failed: %s", e)
        return {}


def build_risk_levels(
    client: OpenAI,
    additive_rows: list[tuple[str, str, str | None]],  # (canonical_id, name, e_number)
) -> dict[str, int]:
    """Score all additives in batches, using cache to avoid repeat LLM calls."""
    if os.path.exists(RISK_CACHE_FILE):
        with open(RISK_CACHE_FILE, "r", encoding="utf-8") as f:
            cache: dict[str, int] = json.load(f)
        log.info("Loaded %d cached risk levels from %s", len(cache), RISK_CACHE_FILE)
    else:
        cache = {}

    uncached = [row for row in additive_rows if row[0] not in cache]
    log.info("%d additives need LLM scoring (%d already cached)", len(uncached), len(cache))

    if uncached and client is not None:
        batches = [uncached[i:i + BATCH_SIZE] for i in range(0, len(uncached), BATCH_SIZE)]
        for batch in tqdm(batches, desc="Scoring additives (LLM)"):
            scores = score_additives_llm(client, batch)
            cache.update(scores)

        with open(RISK_CACHE_FILE, "w", encoding="utf-8") as f:
            json.dump(cache, f, ensure_ascii=False, indent=2)
        log.info("Saved %d risk levels to cache", len(cache))
    elif uncached:
        log.warning("No OpenAI key — assigning risk_level=0 to %d uncached additives", len(uncached))

    return cache


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def seed():
    # 1. Load ingredients.json
    log.info("Loading %s", INGREDIENTS_JSON)
    with open(INGREDIENTS_JSON, "r", encoding="utf-8") as f:
        meta: dict = json.load(f)
    log.info("  %d entries in JSON", len(meta))

    # 2. Parse taxonomy TXT files
    log.info("Parsing %s", INGREDIENTS_TXT)
    ingredients_tax = parse_taxonomy_txt(INGREDIENTS_TXT)
    log.info("  %d entries from ingredients.txt", len(ingredients_tax))

    log.info("Parsing %s", ADDITIVES_TXT)
    additives_tax = parse_taxonomy_txt(ADDITIVES_TXT)
    log.info("  %d entries from additives.txt", len(additives_tax))

    additive_ids: set[str] = set(additives_tax.keys())

    # Merge TXT taxonomies (Russian synonyms only)
    txt_synonyms: dict[str, list[str]] = {}
    for tax in (ingredients_tax, additives_tax):
        for tid, entry in tax.items():
            ru = entry.get("ru", [])
            if tid in txt_synonyms:
                txt_synonyms[tid] = list(set(txt_synonyms[tid]) | set(ru))
            else:
                txt_synonyms[tid] = list(ru)

    log.info("  TXT entries with Russian: %d", sum(1 for v in txt_synonyms.values() if v))

    # 3. Collect all canonical_ids
    all_ids = {k for k in meta.keys() if k.startswith("en:")} | set(txt_synonyms.keys())
    log.info("Combined unique canonical IDs (en: only): %d", len(all_ids))

    # 4. Build rows (without risk_level yet)
    #    row: (cid, name_ru, description, e_number, category, is_allergen, is_additive)
    rows = []
    for cid in sorted(all_ids):
        m = meta.get(cid, {})
        txt_ru = txt_synonyms.get(cid, [])
        json_name_ru = (m.get("name") or {}).get("ru")

        name_ru = pick_best_ru(txt_ru, json_name_ru)
        description = (m.get("description") or {}).get("en")
        e_number = (m.get("e_number") or {}).get("en")
        category = (m.get("additives_classes") or {}).get("en")
        is_allergen = "allergens" in m and bool(m["allergens"])
        is_additive = cid in additive_ids

        rows.append((cid, name_ru, description, e_number, category, is_allergen, is_additive))

    log.info(
        "Rows: %d total, %d additives, %d with e_number, %d with name_ru",
        len(rows),
        sum(1 for r in rows if r[6]),
        sum(1 for r in rows if r[3]),
        sum(1 for r in rows if r[1]),
    )

    # 5. Score additives with LLM
    client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None
    if not client:
        log.warning("OPENAI_API_KEY not set — risk_level will default to 0 for uncached entries")

    additive_input = [
        (cid, cid.removeprefix("en:").replace("-", " "), e_num)
        for cid, _ru, _desc, e_num, _cat, _allergen, is_add in rows
        if is_add
    ]
    risk_levels = build_risk_levels(client, additive_input)

    # 6. Attach risk_level to each row
    final_rows = []
    for cid, name_ru, description, e_number, category, is_allergen, is_additive in rows:
        risk_level = risk_levels.get(cid, 0) if is_additive else 0
        final_rows.append((cid, name_ru, description, e_number, category, is_allergen, is_additive, risk_level))

    # 7. Upsert into DB
    conn = psycopg2.connect(**DB_CONFIG)
    with conn.cursor() as cur:
        cur.execute("ALTER TABLE product_catalog.ingredient ADD COLUMN IF NOT EXISTS name_ru TEXT")
        cur.execute("ALTER TABLE product_catalog.ingredient ADD COLUMN IF NOT EXISTS is_additive BOOLEAN DEFAULT false")
        cur.execute("ALTER TABLE product_catalog.ingredient ADD COLUMN IF NOT EXISTS risk_level SMALLINT DEFAULT 0")

        execute_values(
            cur,
            """
            INSERT INTO product_catalog.ingredient
                (name, name_ru, description, e_number, category, is_allergen, is_additive, risk_level)
            VALUES %s
            ON CONFLICT (name) DO UPDATE SET
                name_ru     = EXCLUDED.name_ru,
                description = EXCLUDED.description,
                e_number    = EXCLUDED.e_number,
                category    = EXCLUDED.category,
                is_allergen = EXCLUDED.is_allergen,
                is_additive = EXCLUDED.is_additive,
                risk_level  = EXCLUDED.risk_level
            """,
            final_rows,
        )
        log.info("Upserted %d ingredient rows", cur.rowcount)

    conn.commit()
    conn.close()
    log.info("Done")


if __name__ == "__main__":
    seed()
