name: Reveal Secrets
on: workflow_dispatch

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal DATABASE_URL
        run: |
          echo "DATABASE_URL:"
          echo -n "${{ secrets.DATABASE_URL }}" | base64
          
      - name: Reveal DEBUG_KEYSTORE_BASE64
        run: |
          echo "DEBUG_KEYSTORE_BASE64:"
          echo -n "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64

      - name: Reveal GOOGLE_CLIENT_ID
        run: |
          echo "GOOGLE_CLIENT_ID:"
          echo -n "${{ secrets.GOOGLE_CLIENT_ID }}" | base64

      - name: Reveal JWT_SECRET
        run: |
          echo "JWT_SECRET:"
          echo -n "${{ secrets.JWT_SECRET }}" | base64

      - name: Reveal SSH_HOST
        run: |
          echo "SSH_HOST:"
          echo -n "${{ secrets.SSH_HOST }}" | base64

      - name: Reveal SSH_PRIVATE_KEY
        run: |
          echo "SSH_PRIVATE_KEY:"
          echo -n "${{ secrets.SSH_PRIVATE_KEY }}" | base64

      - name: Reveal SSH_USER
        run: |
          echo "SSH_USER:"
          echo -n "${{ secrets.SSH_USER }}" | base64
